In [3]:
import desc

In [4]:
import numpy as np
from desc.vmec import VMECIO
from desc.grid import Grid

# woutfile = '/u/npablant/data/w7x/vmec/w7x_ref_172/wout.nc'
woutfile = r"C:\Users\leila\Documents\Visual Studio\pppl_xics_2026\wout.nc"

# 1. Load the VMEC wout file into a DESC Equilibrium object
eq = VMECIO.load(woutfile)


C:\Users\leila\Documents\Visual Studio\pppl_xics_2026\DESC\desc\vmec.py:93: UserWarning: VMEC output appears to be from version 8.48 while DESC is only designed for compatibility with VMEC version 9. Some data may not be loaded correctly.
  warnings.warn(


In [5]:
flux_coord_in = np.array([[0.2, 0.0, 0.2]])
xyz_coord = eq.map_coordinates(
    flux_coord_in, 
    inbasis=("rho", "theta", "zeta"),
    outbasis=("X", "Y", "Z"),
    )
flux_coord_out = eq.map_coordinates(
    xyz_coord, 
    inbasis=("X", "Y", "Z"),
    outbasis=("rho", "theta", "zeta"),
    )

eq.solve()

xyz_coord_solve = eq.map_coordinates(
    flux_coord_in, 
    inbasis=("rho", "theta", "zeta"),
    outbasis=("X", "Y", "Z"),
    )
flux_coord_solve = eq.map_coordinates(
    xyz_coord, 
    inbasis=("X", "Y", "Z"),
    outbasis=("rho", "theta", "zeta"),
    )


Building objective: force
Precomputing transforms
Building objective: lcfs R
Building objective: lcfs Z
Building objective: fixed Psi
Building objective: fixed pressure
Building objective: fixed iota
Building objective: fixed sheet current
Building objective: self_consistency R
Building objective: self_consistency Z
Building objective: lambda gauge
Building objective: axis R self consistency
Building objective: axis Z self consistency
Number of parameters: 2347
Number of objectives: 14112

Starting optimization
Using method: lsq-exact
Optimization terminated successfully.
`ftol` condition satisfied. (ftol=1.00e-02)
         Current function value: 9.496e-07
         Total delta_x: 8.196e-02
         Iterations: 9
         Function evaluations: 12
         Jacobian evaluations: 10
                                                                 Start  -->   End
Total (sum of squares):                                      4.352e-01  -->   9.496e-07, 
Maximum absolute Force error:        

In [6]:
# Set the global print format for floats to 12.6f
with np.printoptions(formatter={'float_kind': '{:12.6f}'.format}):
    print(flux_coord_in)
    print(flux_coord_out)
    print(flux_coord_solve)
    print('')
    print(xyz_coord)
    print(xyz_coord_solve)

[[    0.200000     0.000000     0.200000]]
[[    0.200000    -0.000000     0.200000]]
[[    0.201311    -0.007081     0.200000]]

[[    5.717382     1.158971     0.239574]]
[[    5.717261     1.158946     0.238704]]
